apiVersion: v1
kind: ConfigMap
metadata:
  name: social-agent-config
  namespace: rockbot
data:
  mastodon-enabled: "true"
  mastodon-instance-url: "https://fosstodon.org"
  bluesky-enabled: "true"
  bluesky-handle: "rocky.lhotka.net"
