apiVersion: v1
kind: ConfigMap
metadata:
  name: social-agent-config
  namespace: rockbot
data:
  mastodon-enabled: "true"
  mastodon-instance-url: "https://fosstodon.org"
  bluesky-enabled: "true"
  bluesky-handle: "rocky.lhotka.net"
  threads-enabled: "false"
  threads-include-post-insights: "false"
  public-base-url: "http://social-agent.rockbot.svc.cluster.local"
