// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SocialAgent.Data;

#nullable disable

namespace SocialAgent.Data.Migrations.Npgsql.Migrations
{
    [DbContext(typeof(SocialAgentDbContext))]
    [Migration("20260921233802_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SocialAgent.Core.Models.PollState", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("LastNotificationId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastPollTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastPostId")
                        .HasColumnType("text");

                    b.HasKey("ProviderId");

                    b.ToTable("PollStates");
                });

            modelBuilder.Entity("SocialAgent.Core.Models.SocialNotification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FromHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("PlatformNotificationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedPostId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Type");

                    b.HasIndex("ProviderId", "PlatformNotificationId")
                        .IsUnique();

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SocialAgent.Core.Models.SocialPost", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AuthorHandle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InReplyToId")
                        .HasColumnType("text");

                    b.Property<bool>("IsOwnPost")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformPostId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReplyCount")
                        .HasColumnType("integer");

                    b.Property<int>("RepostCount")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsOwnPost", "CreatedAt");

                    b.HasIndex("ProviderId", "PlatformPostId")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SocialAgent.Core.Models.SocialProfile", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<int>("FollowerCount")
                        .HasColumnType("integer");

                    b.Property<int>("FollowingCount")
                        .HasColumnType("integer");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PostCount")
                        .HasColumnType("integer");

                    b.HasKey("ProviderId");

                    b.ToTable("Profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
